### PR TITLE
Fix unwatch multiple signals

### LINKED ISSUE #2: Batch unsubscribe issue
Once I'm trying to unsubscribe all computeds in the end of render cycle, I got this errors:

image

```log
Cannot read properties of undefined (reading 'liveConsumerNode')
```

```log
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'wrapper')
```

PR to play with: https://github.com/lifeart/glimmer-next/pull/118

How to reproduce:

Open https://deploy-preview-118--g-next.netlify.app/todomvc
Add any todo item
Try to switch between Active/Completed tabs

If I unsubscribe one-by-one, no issue appears:

```js
export const w = new Signal.subtle.Watcher(() => {
    scheduleRevalidate();
});

// works fine
signalsToUnwatch.forEach((signal) => {
  w.unwatch(signal);
});

// breaking
w.unwatch(....signalsToUnwatch);
```

### PR DESCRIPTION
**Pull request by tuhm1**
Fixes #2

The issue arises when removing an element, which shifts the last element to the current index. As a result, the last index goes out of bounds, and the moved element remains unprocessed.

To address this, iterate backward so that the removed element is replaced with a checked element, while the others remain unchanged.

### CODE REVIEW

File: src/wrapper.ts [hunk 1]
```diff
@@ -227,28 +227,25 @@ export namespace Signal {
...
-          if (idx < node.producerNode.length) {
-            const idxConsumer = node.producerIndexOfThis[idx];
-            const producer = node.producerNode[idx];
-            assertProducerNode(producer);
-            producer.liveConsumerIndexOfThis[idxConsumer] = idx;
+
+            // Logic copied from producerRemoveLiveConsumerAtIndex, but reversed
+            const lastIdx = node.producerNode!.length - 1;
+            node.producerNode![i] = node.producerNode![lastIdx];
+            node.producerIndexOfThis[i] = node.producerIndexOfThis[lastIdx];
```
Comment (ds300) [inline src/wrapper.ts:237]: this stuff can be skipped if `lastIdx === i`

File: tests/Signal/subtle/watch-unwatch.test.ts [hunk 2]
```diff
@@ -160,4 +160,34 @@ describe('watch and unwatch', () => {
...
+
+    let expectedNotifyCalls = 0;
+    for (const signal of signals) {
+      signal.set(signal.get() + 1);
+      if (watched.includes(signal)) ++expectedNotifyCalls;
+
+      expect(notify).toHaveBeenCalledTimes(expectedNotifyCalls);
+
+      watcher.watch();
+    }
```
Comment (ds300) [inline tests/Signal/subtle/watch-unwatch.test.ts:191]: i might just add `expect(expectedNotifyCalls).toBe(3)` at the end here just to be clear.

**Review by ds300 — APPROVED** [review]
Makes sense! Thanks for the fix :)

File: tests/Signal/subtle/watch-unwatch.test.ts (hunk 2 above)
Comment (tuhm1) [reply tests/Signal/subtle/watch-unwatch.test.ts:191]: How about `expect(notify).toHaveBeenCalledTimes(3)` directly?

File: src/wrapper.ts (hunk 1 above)
Comment (tuhm1) [reply src/wrapper.ts:237]: You're correct, but I believe it won't make any difference. I prefer to implement only the necessary changes needed to fix the issue, making it easier for the owner to review.

Comment (ds300) [reply src/wrapper.ts:237]: I certainly appreciate that! I also think it would make this code path slightly easier to read if the special case where the producer is the last item in the array was more clearly delineated like it is below the linked snippet.

**Comment by littledan** [comment]
@ds300 Do you recommend landing this change? Does it overlap with/obviate #24?

**Comment by ds300** [comment]
@littledan yeah this is good to land I think. The other PR should be closed, it adds some dubious sanity checks but doesn't fix any bugs as far as I can tell (actually it seems to add code that would swallow legitimate errors in some cases).

**Comment by Roeck** [comment]
@ds300  Just to clarify, I've tested these changes thoroughly, and they don't introduce any new issues. These sanity checks are not meant to hide real errors but to prevent the feature from breaking when it encounters unusual situations.
